In [3]:
import numpy as np

In [550]:
class Calculator:
    value = 0
    def __init__(self):  # 초기화
        # self.value = 0
        pass
    def add(self, *args):
        if len(args) != 0:
            self.value += np.sum(args, dtype = 'i')
        else:
            print('숫자를 입력해주세요')
                                 
    def minus(self, *args):
        if args != ():
            self.value -= np.sum(args, dtype = 'i')
        else:
            print('숫자를 입력해주세요')

    def show_value(self):   
        print(f'현재 값은 {self.value} 입니다.')

In [551]:
c =Calculator()

In [552]:
c.add(100)

In [553]:
c.add([10,20])

In [554]:
c.minus(20,20,20)

In [555]:
c.minus()

숫자를 입력해주세요


In [556]:
c.add()

숫자를 입력해주세요


In [557]:
c.add(range(1,6))

In [558]:
c.show_value()

현재 값은 85 입니다.


In [570]:
x= np.arange(1,10001)
y = np.arange(10001,20001)

In [571]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [566]:
a==b

array([False,  True, False,  True])

In [567]:
a>=b

array([False,  True,  True,  True])

In [572]:
np.all(a==b)

False

In [574]:
np.all(a==c)

True

In [575]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [576]:
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [577]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [579]:
10 * x

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [580]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [582]:
x.sum(axis=0) # axis = 0은 행 간의 연산 결과를 구한다.

array([12, 15, 18, 21])

In [583]:
x.sum(axis=1) # axis =1은 열 간의 연산 결과를 구한다.

array([ 6, 22, 38])

In [584]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [585]:
x.min()

0

In [587]:
np.min(x)

0

In [588]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [589]:
x.min(axis=1)

array([[ 0,  1],
       [10, 11]])

In [590]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [592]:
hasattr(range, '__iter__') # 이 True이면 iterable이라는 의미다.

True

In [593]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [606]:
print(practice.max())
print(practice.sum(axis=1))
print(practice.max(axis=1))
print(practice.mean(axis=0))
print(practice.min(axis=0))

9.0
[32.  30.7 34.3 24.7 29.7]
[8.  9.  8.9 8.2 8.9]
[4.02 5.4  4.72 5.2  5.64 5.3 ]
[0.7 1.1 2.7 2.1 2.8 0.2]


In [607]:
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [608]:
a[j]

array([12, 25, 38, 42])

In [609]:
np.sort(a)

array([12, 25, 38, 42])

In [611]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [658]:
print(a[:,[0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [654]:
scores = np.array([[1,2,3,4],[44,99,100,71],[81,59,90,100]])
scores

array([[  1,   2,   3,   4],
       [ 44,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [675]:
res=np.argsort(scores[1,::])
print(res)

print(scores[:,res])




[0 3 1 2]
[[  1   4   2   3]
 [ 44  71  99 100]
 [ 81 100  59  90]]


1.5

In [685]:
print(np.random.seed(0))
print(np.random.rand(5))
print(np.random.rand(10))
print(np.random.rand(10))

None
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.64589411 0.43758721 0.891773   0.96366276 0.38344152 0.79172504
 0.52889492 0.56804456 0.92559664 0.07103606]
[0.0871293  0.0202184  0.83261985 0.77815675 0.87001215 0.97861834
 0.79915856 0.46147936 0.78052918 0.11827443]


In [700]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [701]:
np.random.shuffle(x)
x


array([7, 8, 6, 5, 0, 3, 2, 4, 1, 9])

In [703]:
np.random.choice(5,5,replace=False) #shuffle 명령과 같다

array([0, 1, 4, 2, 3])

In [705]:
np.random.choice(5,3,replace=False) # 3개만 선택

array([4, 3, 2])

In [712]:
np.random.choice(5,10)

array([0, 0, 1, 2, 0, 3, 1, 1, 4, 0])

In [711]:
np.random.choice(5,10, p=(0.1, 0, 0.3, 0.6, 0)) # 선택 확률을 다르게 해서 10개 선택

array([3, 3, 3, 3, 3, 3, 3, 3, 0, 2])

In [714]:
print(np.random.rand(10))
print(np.random.rand(3,5))

[0.7142413  0.99884701 0.1494483  0.86812606 0.16249293 0.61555956
 0.12381998 0.84800823 0.80731896 0.56910074]
[[0.4071833  0.069167   0.69742877 0.45354268 0.7220556 ]
 [0.86638233 0.97552151 0.85580334 0.01171408 0.35997806]
 [0.72999056 0.17162968 0.52103661 0.05433799 0.19999652]]


In [715]:
print(np.random.randn(10))
print(np.random.randn(3,5))

[-0.66110423 -1.18019102  0.19764264  0.41389998  1.19732198  1.88335386
  0.71422382  2.28433335  1.56410258  0.61110371]
[[-0.87736332 -1.6210875  -0.581673   -0.53783395 -1.55602368]
 [-0.05446484 -1.81127879 -0.63117522 -0.92815918  1.49072192]
 [ 0.19549934 -0.47160433  1.81235465 -2.29413748  0.65120935]]


In [719]:
print(np.random.randint(10, size=10)) 
print(np.random.randint(10, 20, size=10)) # 끝 숫자를 포함하지 않는다.
print(np.random.randint(10, 20, size=(3,5)))

[6 5 0 0 3 1 9 9 6 6]
[17 18 18 17 10 18 16 18 19 18]
[[13 16 11 17 14]
 [19 12 10 18 12]
 [17 18 14 14 11]]


In [791]:
np.random.seed(0)
coin = np.random.randint(0,2, size=100)

print(coin)

np.sum(coin==1)/coin.size

[0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 0
 1 1 0 0 1 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0
 0 1 1 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0]


0.56

In [799]:
np.random.seed(0)
dice = np.random.randint(1,7,100)
print(dice)
dice.mean()
# np.sum(dice)/dice.size

[5 6 1 4 4 4 2 4 6 3 5 1 1 5 3 2 1 2 6 2 6 1 2 5 4 1 4 6 1 3 4 1 2 4 6 4 4
 1 2 2 2 1 3 5 4 4 3 5 3 1 1 5 6 6 1 5 2 5 2 3 3 1 2 2 2 2 4 4 3 4 1 4 6 5
 2 3 5 4 5 5 5 4 5 5 5 1 5 4 3 6 6 6 1 2 6 2 4 1 6 1]


3.42

In [810]:
print(np.unique([11,11,2,22,34,34,34]))
print(np.unique([11,11,2,2,34,34,91], return_counts = True))


[ 2 11 22 34]
(array([ 2, 11, 34, 91]), array([2, 2, 2, 1]))


In [802]:
np.bincount([1,1,2,2,2,3], minlength=6)

array([0, 2, 3, 1, 0, 0])