In [2]:
import numpy as np

In [9]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
ar.shape

(10,)

In [12]:
type(ar)

numpy.ndarray

In [13]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [18]:
# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
# 그래서 시퀀스 자료형 중 제일 큰 값이 U5이지만 U8로 타입이 지정되었다.

ar5= np.array(['가나다라마','바사아','자', '차카'],'U8')
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형이다.

['가나다라마' '바사아' '자' '차카']
<U8


In [24]:
x = np.array([1,2,3], dtype='f')
print(x.dtype)
print(x[0] + x[1])

float32
3.0


In [23]:
x = np.array([1,2,3], dtype='U')
print(x.dtype)
print(x[0] + x[1])

<U1
12


In [25]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ans = [2*d for d in data]
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
list_samp = [_ for _ in range(3)]
print(list_samp *5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [30]:
c= np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
c.shape

(2, 3)

In [34]:
c= np.array([[10,20,30,40],[50,60,70,80]])
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [40]:
c= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]).reshape(2,3,4)
print(c)
print(c.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [41]:
a = np.array([_ for _ in range(5)])
a

array([0, 1, 2, 3, 4])

In [42]:
a[2]

2

In [44]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
a[0,:] # 첫번째 행 전체

array([0, 1, 2])

In [46]:
a[:,1] # 두번째 열 전체

array([1, 4])

In [47]:
a[1,1:] # 두번째 행의 두번째 열부터 끝열까지

array([4, 5])

In [48]:
a[:2,:2]

array([[0, 1],
       [3, 4]])

In [118]:
m = np.array([_ for _ in range(15)]).reshape(3,5)
print(m)
print(m[1,2])
print(m[2,4])
print(m[1,1:3])
print(m[1:,2])
print(m[:2,3:])
print(m[m==7])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]
[7]


In [106]:
d = np.zeros(5, dtype = 'U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [107]:
d[0]='abc'
d[1]='abcd'
d[2]='ABCDE'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [108]:
e = np.ones((2,3,4), dtype = 'i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [109]:
f = np.ones_like(e, dtype = 'f')
f

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [110]:
g= np.empty((4,3))
g

array([[0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125]])

In [111]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.arange(3,21,2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [121]:
np.linspace(0,100,15, dtype='i') # 시작,끝(포함), 갯수

array([  0,   7,  14,  21,  28,  35,  42,  50,  57,  64,  71,  78,  85,
        92, 100], dtype=int32)

In [123]:
np.logspace(0,100,5) # 시작,끝(포함), 갯수

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [126]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [129]:
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [147]:
b= a.reshape(3,2,-1) # -1을 사용하면 알아서 맞춰줌
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [148]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
a1 = np.ones((3,2))
a2 = np.zeros((3,3))

In [152]:
np.hstack([a1,a2])

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [153]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))

In [154]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [155]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))

In [156]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [157]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [158]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [162]:
a= np.array([[0,1,2],[3,4,5]])
print(np.tile(a,2))
print(np.tile(a, (3, 2)))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [1]:
a= np.zeros((3,3))
b= np.ones((3,2))
c = np.hstack((a,b))
d = np.arange(10,160,10).reshape(3,-1)
e = np.vstack((c,d))
print(np.tile(e,(2,1)))

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]
